const HOME_PRICE_COINS = 1000;
const HOME_CANVAS_WIDTH = 600;
const HOME_CANVAS_HEIGHT = 840;
const HOME_SINGLE_SLOTS = ['wall_base', 'floor_base', 'floor_cover', 'foreground_item'];
const HOME_MULTI_SLOT = 'back_decor';
const HOME_ALLOWED_SLOTS = [...HOME_SINGLE_SLOTS, HOME_MULTI_SLOT];
const HOME_STARTER_WALL_ITEM_ID = 'home_wall_base_empty_starter';
const HOME_FRIDGE_DECOR_ITEM_ID = 'home_back_decor_old_red_fridge';
const HOME_BUILTIN_WALL_PATH = '/sprites/basewall.png';
const HOME_BUILTIN_FLOOR_PATH = '/sprites/basefloor.png';
const HOME_PEEPER_SIZE = 337;
const HOME_PEEPER_CENTER_X = HOME_CANVAS_WIDTH / 2;
const HOME_PEEPER_CENTER_Y = 584;
const VISIT_HOME_PEEPER_SIZE = 212;
const VISIT_HOME_VIEWER_CENTER_X = 172;
const VISIT_HOME_OWNER_CENTER_X = 428;
const VISIT_HOME_PEEPER_CENTER_Y = 551;

module.exports = {
  HOME_PRICE_COINS,
  HOME_CANVAS_WIDTH,
  HOME_CANVAS_HEIGHT,
  HOME_SINGLE_SLOTS,
  HOME_MULTI_SLOT,
  HOME_ALLOWED_SLOTS,
  HOME_STARTER_WALL_ITEM_ID,
  HOME_FRIDGE_DECOR_ITEM_ID,
  HOME_BUILTIN_WALL_PATH,
  HOME_BUILTIN_FLOOR_PATH,
  HOME_PEEPER_SIZE,
  HOME_PEEPER_CENTER_X,
  HOME_PEEPER_CENTER_Y,
  VISIT_HOME_PEEPER_SIZE,
  VISIT_HOME_VIEWER_CENTER_X,
  VISIT_HOME_OWNER_CENTER_X,
  VISIT_HOME_PEEPER_CENTER_Y,
};
